spring:
    application:
        name: gymtracker-api

    datasource:
        url: jdbc:postgresql://localhost:5433/gymtracker
        username: gymtracker
        password: gymtracker

jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000